
services:
  attenzio_database:
    build:
      context: ./database
      dockerfile: Dockerfile
    env_file:
      - ./database/.env
    container_name: attenzio_database
    ports:
      - 5432:5432
    networks:
      - bst_network
    volumes:
      - ./database/volume:/var/lib/postgresql/data:rw
    healthcheck:
      test: ["CMD-SHELL", "PGPASSWORD=jonmeister pg_isready -U jonmeister -d attenzio_database -h attenzio_database"]
      interval: 10s
      timeout: 5s
      retries: 2
  attenzio_backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    env_file:
      - ./backend/.env
    container_name: attenzio_backend
    expose:
      - 8000
    ports:
      - 8000:8000
    networks:
      - bst_network
    depends_on:
      attenzio_database:
        condition: service_healthy
    links:
      - attenzio_database:attenzio_database

  attenzio_frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    env_file: 
      - ./frontend/.env
    container_name: attenzio_frontend
    restart: always
    depends_on:
      - attenzio_backend
    ports:
      - "3000:80" # 3000:3000
    networks:
      - bst_network

networks:
  bst_network:
    driver: bridge
